### ISSUE TITLE
Merge header2.0 into master

### ISSUE THREAD

**Issue by wrd90** [HSR-Stud/header#6]
Wäre es nicht besser, wenn wir langsam mal den header2.0 branch in den master mergen? Die Idee ist ja laut Readme, dass für neue Zusammenfassungen nur noch der header2.0 verwendet wird, und im master gab es ja scheinbar seit 6 Jahren keine commits mehr.

Zusammenfassungen, die noch mit dem master branch arbeiten werden ja davon grundsätzlich nicht betroffen sein, die können ja immernoch mit diesem Stand arbeiten wenn sie wollen.

**Comment by wrd90** [comment]
Ich kann das gerne auch übernehmen.

**Comment by LMazzole** [comment]
Neue Zusammenfassungen verwenden den header als Submodul meistens nicht mehr.  
Du kannst ihn gerne noch mergen, ich würde aber nicht mehr all zu viel Zeit darin investieren.  
Um keine Kompatibilitätsprobleme mit alten Zusammenfassungen zu erhalten wäre es evt. sinnvoll das Repo sogar zu archivieren.

**Comment by wrd90** [comment]
Interessant, da bin ich wohl noch von der alten Garde :) Weshalb verwenden sie den Header nicht mehr?

**Comment by LMazzole** [comment]
Es gab in der Vergangenheit einige Probleme mit dem Download der Submodule sowie eine gewisse Unsicherhiet, was wo angepasst werden darf und kann ohne die anderen Zusammenfassungen zu beeinträchtigen.  
Momentan wird oft einfach die [VorlageZFLaTex](https://github.com/HSR-Stud/VorlageZFLaTex) verwendet, welche einen Teil des "alten" Headers nutzt.

**Comment by wrd90** [comment]
Hmm, das finde ich aber nicht sehr praktisch... Ich bin der Meinung, dass gemeinsame Teile immernoch gemeinsam maintained werden sollten, oder nicht? Wenn es Unklarheiten gibt, sollten die auf jeden Fall geklärt werden, jedoch sollte das nicht die Struktur und Professionalität der Repos beeinflussen. Meiner Meinung nach sollte dann auch das Repo [VorlageZFLatex](https://github.com/HSR-Stud/VorlageZFLaTex) diese Module ([header](https://github.com/HSR-Stud/header), [idiotenseite](https://github.com/HSR-Stud/idiotenseite) und (Travis)[https://github.com/HSR-Stud/Travis]) als Submodule beinhalten.

**Comment by LMazzole** [comment]
Ich stimme dir teilweise zu. Das Problem hier ist halt, dass es für Neueinsteiger viel komplizierter ist und die Hemmschwelle überhaupt eine Zusammenfassung in LaTex mit Github zu schreiben stiegt. Deshalb wurde die Vorlage bewusst einfach gehalten und diese "extras" weggelassen.

**Comment by wrd90** [comment]
Da hast du natürlich recht, allerdings finde ich, dass diese Einsteiger ja nicht immer Einsteiger bleiben sollen :)
Es ist natürlich kein schlechter Ansatz, diese Vorlage einfach und knapp zu halten, jedoch denke ich, dass es sehr einfach wäre, im Readme der [Vorlage](https://github.com/HSR-Stud/VorlageZFLatex) und im [Willkommen](https://github.com/HSR-Stud/Willkommen) eine Schritt-für-Schritt anleitung mit den git commands hinzuzufügen, inklusive denen, die man für die Submodules benötigt. Wenn man git verwendet, wird man früher oder später auch darüber stolpern.

Meiner Meinung nach gibt es zwei Möglichkeiten:

- Entweder wir lassen den Header und die Idiotenseite so wie sie sind (nicht als submodule) in der Vorlage, und die "Erfahrenen" Nutzer gehen ab und zu durch die Repos und fügen diese irgendwann als submodules hinzu.
- Oder wir fügen diese jetzt schon als Submodule in die Vorlage mit einer Anleitung, wie man diese verwendet.

Egal wie wir das machen, finde ich sollte diese Anleitung in der Vorlage und im [Willkommen](https://github.com/HSR-Stud/Willkommen) hinzugefügt werden.
Zusätzlich sollte in beiden Repos das Vorgehen mit submodules und deren Sinn&Zweck beschrieben werden. Der ursprüngliche Gedanke war ja, genau den Stil und das Aussehen der HSR-ZF gleich zu halten, wenn wir jetzt in jedem Repo das anders machen, wird das total über den Haufen geworfen.

**Comment by wrd90** [comment]
Fixed by 504e255c
